### ISSUE TITLE
Watermark displays incorrectly

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#134]
**Describe the bug**

With a simple 3-vertex pipeline with `generator` source, start it with only the source with replica=1, and the other vertices with 0 replica. It is expected only the source vertex replica to show timestamp moving, however from the screenshot below, the 2nd vertex shows the same watermark, which is wrong.

<img width="1215" alt="Screen Shot 2022-08-08 at 5 58 59 PM" src="https://user-images.githubusercontent.com/2832028/183540855-ad388a59-3107-45fe-9018-8eb783288e91.png">

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
is this is caching issue on the UI? or is our backend returning number for a vertex that has been scaled down?

**Comment by KeranYang** [comment]
As new data comes in, the **input** vertex populates the offset timeline store(otStore) to save most recent timestamps for each of the offsets. With the graph above, assuming we never had any active PODs for **p1** and **output** vertices, the system is in a state where otStore populated by **input** is growing and otStores to be populated by **p1** and **output** are empty.

The deamon service uses fetchers to grab vertex's level watermarks and shows them at front-end. In our current implementation, watermark fetcher for vertex Vn gets watermark from the otStore that is populated by vertex Vn-1. Therefore, the watermark showing on vertex Vn, is the most recent timestamp that ALL data before/at that timestamp has been **processed by Vn-1** and **ready for Vn to process**. That's why although the 2nd vertex has 0 pod and never had processed any data, it still has a moving watermark.

I had a discussion with @whynowy and we think that watermark for Vn should be the timestamp before which all data has already been **processed** by Vn, instead of being **ready to be processed** by Vn.

The change could be to update the daemon service to fetch watermarks using publishers instead of fetchers. Investigating...
