### ISSUE TITLE
`source` and `sourceTransformer` sdk use the same serverInfoPath

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#1456]
**Describe the bug**
In the SDKs, `source` and `sourceTransformer` use the same serverInfoPath, this will potentially cause problem.

We should use different path for different sdks maybe.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by KeranYang** [comment]
@a3hadi will pick up this issue.

**Comment by a3hadi** [comment]
@whynowy I just had a quick question. Is this a problem because two separate containers would write to the same location? I.e., would a container containing a python udf and a container containing a java udf both write to /var/run/numaflow/server-info and this could potentially cause a conflict? If this is the case, should we address this just for the sourcer service?

**Comment by whynowy** [comment]
> @whynowy I just had a quick question. Is this a problem because two separate containers would write to the same location? I.e., would a container containing a python udf and a container containing a java udf both write to /var/run/numaflow/server-info and this could potentially cause a conflict? If this is the case, should we address this just for the sourcer service?

Potentially there could be 2 containers write to the same location (e.g. udsource and source transformer).

What we should do is, for different type of UD container, use different path (instead of only addressing source and transformer).

**Comment by a3hadi** [comment]
steps to take:

1. Create new paths for all UD services, and use these new paths in all SDKs
2. Implement the same changes on the client side in numaflow
3. Update all images with new version number so that they use the new paths
4. Add note to documentation/readme that users using new SDK version also update numaflow to new version, otherwise there will be compatibility issues

**Comment by KeranYang** [comment]
Great job @a3hadi on closing this issue. 👍
