### ISSUE TITLE
move watermark at millisecond granularity

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#201]
Currently, the watermark is progressing at second granularity. This is too slow for near-realtime systems. Please make sure the progression at the millisecond level will not affect the overall load on the watermark store.

Tasks 
- [ ] write a proposal on what it takes to make watermark progress at the millisecond level
- [ ] implement millisecond progression

**Comment by chromevoid** [comment]
> what it takes to make watermark progress at the millisecond level

We need to update wherever time.Unix() to time.UnixMilli() in the watermark implementation. 
Moving time unit from second to millisecond will increase the total number kv pairs in the OT bucket.

**Comment by ashwinidulams** [comment]
should we consider updating the watermarks periodically instead? would give us some lever to handle scale when we have too many pods / parallelism

**Comment by chromevoid** [comment]
The "Watermark is ignored" doesn't really caused by the time unit (using simple pipeline)

# Observation
(The _(?*)_ mark below means: Not sure if this case can be considered as delayed.. not fully understand how forward a chunk works..)

The tickgen generates the 5 messages per second, and uses the last message's readOffset as the watermark. You can see from below screenshot that the tickgen's publish watermark is working properly (almost every second there's a new watermark).
The issue is the forwardAChunk. Looks like the messages sometimes get delayed _(?*)_, and the last message in the chunk is still a previous watermark. `FORWARD A CHUNK 1666849259269 2022-10-27T05:40:59.269Z (DELAYED)`
<img width="675" alt="image" src="https://user-images.githubusercontent.com/19543684/198206047-8a3c19cd-b1c7-4689-a829-b80acebbb85b.png">

After a while, at some point, the tickgen-generated watermark gets skipped, and the forwardAChunk again gets a delay_(?*)_
<img width="708" alt="image" src="https://user-images.githubusercontent.com/19543684/198208117-00e1393c-0029-473d-9a07-1231dbb10dd3.png">


A pdf version of above logs.
[logs.pdf](https://github.com/numaproj/numaflow/files/9876374/logs.pdf)

**Comment by chromevoid** [comment]
If the above forwardAChunk behavior is expected, then (I think) the `New watermark is ignored` log message is valid and can't be avoided in our current implementation.
