### ISSUE TITLE
Flaky E2E tests caused by port-forward and logs streaming

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#210]
Using port-forward to verify the testing results from Pod logs is widely used in E2E tests, which became unreliable recently - sometimes it fails with message like below, which means streaming logs fails, and usually a retry makes through.

```
Watching POD: simple-pipeline-watermark-cat3-0-np6xu
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-watermark-cat3-0-np6xu/main?follow=true": EOF    functional_test.go:180: Expected vertex pod log contains "Start processing udf messages"
```

This issue could be caused by:

1. The runner instances assigned by Github action has limited resources - this issue started to happen after we had more test cases;
2. Unknown bugs in our code - log streaming or port-forward not released?
3. k3s version matters (v1.21 worked well, v1.21+ became flaky).

Long termly, we need to figure out a way to run E2E tests with a new approach.

**Comment by vigith** [comment]
I would say, let's fix this issue once and for all. Port-Forwarding is not a scalable and reliable approach. We can do E2E within the cluster and then export the results outside (perhaps via HTTP protocol). The results will have to be exported because we need to mark the result of the run as successful or not.

**Comment by KeranYang** [comment]
### Investigation Notes

#### Observations
1. E2E tests became flaky after we added the sdks-e2e tests on Oct 5th. https://github.com/numaproj/numaflow/pull/197
2. The most frequent error is ,as mentioned above, the EOF error.
3. Such error can happen on any test cases, not on a specific one.

```
1. e2e
TestFunctionalSuite/TestCreateSimplePipeline
Watching POD: simple-pipeline-output-0-tqvm9
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-output-0-tqvm9/main?follow=true": EOF    functional_test.go:37: Expected vertex pod log contains "\"Data\":\".*\",\"Createdts\":.*"

TestFunctionalSuite/TestWatermarkEnabled
Watching POD: simple-pipeline-watermark-output1-0-ldsz9
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-watermark-output1-0-ldsz9/main?follow=true": EOF    functional_test.go:184: Expected vertex pod log contains "\"Data\":\".*\",\"Createdts\":.*"

2. http-e2e
TestHTTPSuite/TestHTTPSourcePipeline

Watching POD: http-source-out-0-jhftk
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/http-source-out-0-jhftk/main?follow=true": EOF    http_test.go:57: Expected vertex pod log contains "with-id"
    panic.go:522: Terminating port-forward for POD http-source-in-0-pcyom
    panic.go:522: Deleting Pipeline http-source

3. sdks-e2e
Watching POD: flatmap-python-udsink-0-2fnb8
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/flatmap-python-udsink-0-2fnb8/udsink?follow=true": EOF    sdks_test.go:42: Expected vertex pod log contains "hello"
    panic.go:522: Terminating port-forward for POD flatmap-in-0-j7j2b
    panic.go:522: Deleting Pipeline flatmap
```
4. In the .github CI workflow yaml file, increasing max-parallel from 4 to 5 didn't help.
5. Adding retry on https://github.com/numaproj/numaflow/blob/c85f2613c2da665b00e29c54783b2e30997e4e9b/test/fixtures/util.go#L358 resolves the EOF error and the E2E tests can succeed.
6. There are E2E test failures caused by other reasons, but relatively infrequent.
* https://github.com/KeranYang/numaflow/actions/runs/3333807965/attempts/1
* https://github.com/KeranYang/numaflow/actions/runs/3333807965/jobs/5516513871
* Installing Numaflow step sometimes fails as well. https://github.com/KeranYang/numaflow/actions/runs/3338196173/jobs/5525542415

**Comment by KeranYang** [comment]
With my PR getting merged, this issue was automatically resolved. Although the errors listed in the initial post has been fixed, we still have open topics coming out of this issue that are not resolved. I am going to create separate issues to address them.

Topic 1: mentioned by Vigith
> I would say, let's fix this issue once and for all. Port-Forwarding is not a scalable and reliable approach. We can do E2E within the cluster and then export the results outside (perhaps via HTTP protocol). The results will have to be exported because we need to mark the result of the run as successful or not.

Topic 2: Fix the infrequent E2E failure cases.
