### ISSUE TITLE
User Defined Transformer and Filter

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#446]
## Tasks

- [x] #462
- [x] #464
- [x] #463
- [x] #465
- [x] #498 
- [x] #506
- [x] #502 
- [x] #514
- [x] #515
- [x] #530
- [x] #589  

---
There are two primary reasons we need to have a container and/or built-in at the source vertex. It all boils down to the fact that the payload (message) is completely opaque to the Numaflow platform. For the same reason, we use user-defined functions to apply map/reduce transformations/aggregations and have support for user-defined sinks for persisting messages. We need to extend this feature to the source vertex for the following benefits.

# Benefits

## Filter
Today the source has to read and forward all the messages to the UDF vertex to filter out the unwanted messages. This decision could have been made at the source itself if we had a way to plug in user code (or expression). Filter at source can reduce the cost of operation, especially if we are discarding a lot of messages, e.g., ML pipelines will discard all the sparse data.

## Watermark Assignment
The watermark is assigned at the source from the event time of the payload. Since the payload itself is opaque to Numaflow, it cannot retrieve event time from the payload. This affects the correctness of the processing because we have to rely on other mechanisms to derive the most appropriate and closest event time relevant to data (e.g., LOG_APPEND_TIME of Kafka for Kafka source, custom HTTP header for HTTP source, etc.) 

# Proposal

Build a User Defined Deserializer and Filter feature at the source that can convert the incoming payload/message into a 3-valued tuple of (`time`, `key`, `value`) of the kind `flatmap` transformation (0 or more results).

If we can also provide two built-in functions, `filter` and `eventTime`, we can improve user experience if the payload is in JSON format.

**Comment by KeranYang** [comment]
## Investigation Notes

### Current states

source data -> data transformation implemented by each type of source -> `isb.ReadMessage`

#### Data flow

* Step 1: Source vertices listen to the corresponding data source.
* Step 2: Transform the incoming data to `isb.ReadMessage`.
* Step 3: Send the `isb.ReadMessage` to the outgoing ISB.

By the time source data gets processed and sent to outgoing ISB, the data is in the following unified format. (`isb.ReadMessage`)

```markdown
Header
* PaneInfo (the time window of the payload)
  * EventTime
  * StartTime
  * EndTime
  * IsLate bool
* ID (used for exactly-once-semantics)
* Key
Body
* Payload []byte
```

We want to make changes to Step 2 to allow users to specify how they want to perform the data transformation.

#### Diving into step 2 - Transform the incoming data to `isb.ReadMessage`

For all of our existing types of source, the data transformation step generally implements 3 functionalities.

1. Assign EventTime.
2. Assign Payload.
3. Return the transformed `isb.ReadMessage`

```go
// A nats example of transforming a natslib.Msg to an isb.ReadMessage

if sub, err := n.natsConn.QueueSubscribe(source.Subject, source.Queue, func(msg *natslib.Msg) {
		id := uuid.New().String()
		// Keran's notes: here is where we can derive data from input source data.
		m := &isb.ReadMessage{
			Message: isb.Message{
				Header: isb.Header{
					PaneInfo: isb.PaneInfo{EventTime: time.Now()},
					ID:       id,
				},
				Body: isb.Body{
					Payload: msg.Data,
				},
			},
			ReadOffset: isb.SimpleStringOffset(func() string { return id }),
		}
    // Keran's notes: here is where we can determine if we are gonna filtering out a message if we surround the following statement with an if.
    // (e.g. if after transformation m is nil then return without sending to channel)
  	n.messages <- m
	});
```

### Target states

If users don't specify User Defined Deserializer(UDD), we continue using the default approach to transform data.

Otherwise we use UDD to first tranform the data into a flat map, then numaflow transforms the flat map to `isb.ReadMessage`. The reason why we don't directly tranform to `isb.ReadMessage` is for de-coupling. If we ask UDD to directly generate `isb.ReadMessage`, any changes to `isb.ReadMessage` schema will potentially require upgrades on all existing UDDs, which is not scalable.

#### Template Spec (using http source as example)

```yaml
spec:
  vertices:
    - name: in
      source:
        http: {}
        transform:
          image: "A user defined deserializer image to transform a http payload byte[] to a flat map"
```

#### Random Thoughts

1. Can we delegate the following functionality to the UDD image itself?

> If we can also provide two built-in functions, `filter` and `eventTime`, we can improve user experience if the payload is in JSON format.

The following UDD takes a JSON data `payload`, sets the eventTime as `payload.event_time` and filters out data with `int(payload.id)>=100`

```yaml
spec:
  vertices:
   - name: in
     source:
       http: {}
       transform:
         image: "A user defined deserializer image to transform a JSON data to a flat map, with filtering"
           command: ["transform"]
           args: ["--eventtime", "payload.event_time", "--filter", "int(payload.id)<100"]
```

This way we can have a single generic JSON UDD image that allows multiple pipelines to specify their own customized transformation logics. The main benefit is that we delegate all the tranformation logics to the UDD itself and the main numaflow only expects a returned flat map.

2. Should source vertex care about assigning a key to a message?

Although in this task we give source vertex the capability to do so, it's probably better to let following UDF map vertices to take care of assigning keys to messages, to follow single responsibility principle. (It's up to the user.)

**Comment by KeranYang** [comment]
Closing as all sub-tasks are done.
