### ISSUE TITLE
reduce should use a persistent store by default

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#449]
Today the default store is an in-memory store. Data will be lost during pod migrations and restarts. We should use WAL by default and can give the option to override to in-memory store if required (not recommended though).

**Comment by whynowy** [comment]
PVC is mostly immutable, which means once created, it can not be updated. Also, `default` storage class is not available in some of the GKE cases.

I recommend:

1. Default to use `emptyDir` when `storage` is missing, so that we can alway use `wal` pbq;
2. Add a section in the reduce document, explicitly mentioning `persistentVolumeClaim` is needed to run real workloads, if that's missing, `emptyDir` is used, and that might cause data loss.
3. Update our examples to add `persistentVolumeClaim`.
