### ISSUE TITLE
kill switch to drop messages when buffer.isFull == true

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#524]
# Summary

We need to have an edge level setting to drop the messages if the `buffer.isFull == true`. Even if the UDF or UDSink drops a message due to some internal error in the user-defined code, the processing latency will spike up causing a natural back pressure. A kill switch to drop messages can help alleviate/avoid any repercussions on the rest of the DAG. 

This setting is an edge-level setting and can be enabled by `dropOnFull` to `true` (default is `false`).
```yaml
  edges:
    - from: a
      to: b
      dropOnFull: true
```

# Use Cases

**NOTE**: This is a data loss scenario but can be useful in cases where we are doing user-introduced experimentations, like A/B testing, on the pipeline. It is totally okay for the experimentation side of the DAG to have data loss while the production is unaffected.

# Considerations
We could use add a `onFull` (instead of `dropOnFull`) flag which could take different values like `drop`, `retry` (current behavior), etc. This will enable us to support other experiences like writing to dlq, etc in the future if we ever need those.

**Comment by KeranYang** [comment]
Adding initial investigation notes.

### Current Behaviour

I checked 3 ISB implementations, **JetStream**, **Redis** and **In-Memory** Buffer. They all use the same logic when writing to a full buffer. It's as follow:

When forwarder(applying to both `reduce` and `non-reduce`) tries to write-to-buffer a batch of messages, if the ToBuffer is full, the entire batch will be marked as failed with `BufferWriteErr`. Then it will keep retrying the batch until all the messages are successfully processed. The forwarder **DO NOT acknowledge** the batch read offsets until all of them are successfully processed.

In short, as vigith mentioned above, current `onFull` is `retryUntilSuccess`.

### The DropOnFull behaviour

From my understanding, the **DropOnFull** behaviour, translating to `onFull`, is `dropAndAcknowledge`. If we drop messages without acknowledging, the batch will still get re-processed later, which contradict with the purpose of this task.

### Implementation Plan

* I will introduce the `onFull` edge level specification as Enum. (It will also be available at pipeline level and allow edge level to override. Like `bufferUsageLimit `)
  * Two enums for now: `retryUntilSuccess` and `dropAndAcknowledge`.
* All 3 existing buffer writer implementations support `options`, I will add a `WithOnFullAction(action enum)` to each of them such that writer can use it to determine how to handle a full buffer.
* Inside the `Write()` implementation, if the buffer is full and the `OnFullAction` is specified as `dropAndAcknowledge`, I will set the return values `([]isb.Offset, []error)` as both `nil, nil`. Setting the returned `writeOffsets` slice as `nil` is because we didn't write any of these messages to ToBuffer, hence we should't be able to get any write offsets, let alone to publish watermarks. Setting the `[]error` slice as `nil` is to avoid retrying.

@vigith @whynowy , am I on the right track?

**Comment by vigith** [comment]
will it be easier if you add an error type check in https://github.com/numaproj/numaflow/blob/main/pkg/forward/forward.go#L496? this way you do not have to edit any of the buffers' `Write()` method.

**Comment by vigith** [comment]
Perhaps we can write a generic wrapper around the `Write` to generalize the Write code path with retries, etc. Today `forward` and `reduce` has separate Write paths, and we will have to handle those independently.

**Comment by whynowy** [comment]
1. `dropAndAckLatest` instead of `dropAndAcknowledge `.
2. It's a good idea to do it in forwarder as @vigith mentioned.
